package com.dsu.extended.preparation

enum class InstallationStep {
    // Initial value
    NOT_INSTALLING,

    // When a DSU is detected on app startup
    DSU_ALREADY_INSTALLED,
    DSU_ALREADY_RUNNING_DYN_OS,

    // Preparation steps
    PROCESSING,
    COPYING_FILE,
    DECOMPRESSING_XZ,
    COMPRESSING_TO_GZ,
    DECOMPRESSING_GZIP,
    EXTRACTING_FILE,
    VALIDATING_IMAGE,

    // Installation Steps
    REQUIRES_ADB_CMD_TO_CONTINUE,
    DISCARD_CURRENT_GSI,
    WAITING_USER_CONFIRMATION,
    PROCESSING_LOG_READABLE,
    INSTALLING,
    INSTALLING_ROOTED,
    CREATING_PARTITION,

    // Success states
    INSTALL_SUCCESS,
    INSTALL_SUCCESS_REBOOT_DYN_OS,

    // General errors
    ERROR,
    ERROR_CANCELED,
    ERROR_REQUIRES_DISCARD_DSU,
    ERROR_ALREADY_RUNNING_DYN_OS,
    ERROR_CREATE_PARTITION,
    ERROR_EXTERNAL_SDCARD_ALLOC,
    ERROR_NO_AVAIL_STORAGE,
    ERROR_F2FS_WRONG_PATH,
    ERROR_EXTENTS,
    ERROR_SELINUX,
    ERROR_SELINUX_ROOTLESS,

    // NEW: Enhanced boot diagnostic errors
    ERROR_AVB_VERIFICATION,
    ERROR_PARTITION_TABLE,
    ERROR_GSI_INCOMPATIBLE,
    ERROR_KERNEL_MISMATCH,
    ERROR_BOOTLOOP_DETECTED,
    ERROR_INSUFFICIENT_RAM,
    ERROR_VENDOR_MISMATCH,
    ERROR_DM_VERITY,
    ERROR_SYSTEM_SERVER_CRASH,
    ERROR_BOOT_TIMEOUT,
    ERROR_SUPER_PARTITION,
    ERROR_SLOT_SWITCH,
    ERROR_FIRMWARE_MISMATCH,
    ERROR_TREBLE_INCOMPATIBLE,
    ERROR_VNDK_MISMATCH,
    ERROR_CPU_ARCH_MISMATCH,
    ERROR_UNKNOWN_BOOT_FAILURE,
}
